refactor(jobs,piplines):  tidb verify ci jobs `ghpr_build` and `ghpr_unit_test`
* refactor(jobs/ci/pingcap/tidb): fix job DSL

error: "ERROR: (unknown source) the following options are required and must be specified: msgSuccess, msgFailure, commitStatusContext"

* refactor(jobs/ci/pingcap/tidb): enable job `wip_tidb_ghpr_build`

* refactor(jobs/ci/pingcap/tidb): try to disable git status update for `wip_tidb_ghpr_build`

* refactor(jobs/ci/pingcap/tidb): try to disable git status update for `wip_tidb_ghpr_build`

* refactor(jobs/ci/pingcap/tidb): try to disable git status update for `wip_tidb_ghpr_build`

* refactor(pipelines/pingcap/tidb/release-6.2): build pipeline refactor update

* test(jobs/ci): usging feature branch to test

* test(jobs/ci): usging feature branch to test

* test(pipelines): fix pipeline

* chore(jobs/ci/pingcap/tidb): add debug lines

* test(jobs/ci): usging feature branch to test

* test(pipelines): fix pipeline

* test(jobs/ci): avoid report with `default` context

* feat(jobs/ci/pingcap/tidb/release-6.2): limit branch and changes regions

* refactor(jobs): rename job DSL paths

* feat(jobs): add folders

- pingcap
- pingcap/tidb
- pingcap-qe

* fix(jobs/pingcap/tidb/latest): fix regex escaping

* refactor(jobs): job positions and DSL paths

* fix(jobs): script name and folders

* feat(pipelines/pingcap/tidb): add ghpr_unit_test pipeline

* refactor(pipelines/pingcap/tidb): delete nfs volume in `ghpr_build`

* refactor(pipelines/pingcap/tidb): delete useless post steps

* refactor(pipelines/pingcap/tidb): make more clean in ghpr_build

* feat(pipelines/pingcap/tidb): simplfy ghpr_unit_test pipeline

* fix(pipelines/pingcap-qe/ci): fix job pipeline def

* feat(jobs/pingcap/tidb/latest): add job `ghpr_unit_test.groovy`

* fix(pipelines/pingcap-qe/ci): fix job pipeline def

* feat(pipelines/pingcap/tidb): sh step scripts

* fix(jobs/pingcap/tidb): fix whitelist target branch regexes

* chore(jobs/pingcap/tidb): add fixme comments

* chore(jobs/pingcap/tidb): simple regex

* fix(pipelines/pingcap/tidb): pipeline ghpr_unit_test

* feat(pipelines/pingcap/tidb): set timeout to 20 min for pipeline `ghpr_unit_test`

* fix(pipelines/pingcap/tidb): pipeline ghpr_unit_test

* chore(pipelines/pingcap/tidb): update comment's todo assigner

* fix(jobs/pingcap/tidb): solve conflicts of `excludedRegions`

* feat(jobs/pingcap/tidb): enable jobs

- ghpr_build
- ghpr_unit_test