fix(pipeline): skip tidb-test checkout cache (#4635)
### Changed
skip the Jenkins pipeline cache wrapper around the `tidb-test` checkout
.

### Why

Recent builds were failing in `Checkout` while restoring
`git/PingCAP-QE/tidb-test/rev-` cache with:

```
java.io.IOException: unexpected EOF with 3072 bytes unread
Caused: java.io.IOException: Failed to extract input stream
```

Direct checkout avoids the corrupted prefix cache while keeping the job
runnable.

### Validation
-
https://prow.tidb.net/jenkins/job/pingcap-inc/job/tidb/job/release-8.5/job/pull_mysql_test/35/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/merged_common_test/268/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/merged_integration_jdbc_test/268/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/merged_integration_mysql_test/261/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/merged_integration_python_orm_test/273/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/merged_sqllogic_test/268/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/pull_common_test/21/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/pull_integration_ddl_test/9/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/pull_integration_jdbc_test/21/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/pull_integration_mysql_test/23/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/pull_integration_nodejs_test/3/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/pull_integration_python_orm_test/17/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/pull_sqllogic_test/10/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/release-8.5/job/pull_common_test/7/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/release-8.5/job/pull_integration_common_test/5/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/release-8.5/job/pull_integration_ddl_test/9/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/release-8.5/job/pull_integration_jdbc_test/8/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/release-8.5/job/pull_integration_nodejs_test/5/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/release-8.5/job/pull_integration_python_orm_test/5/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/release-8.5/job/pull_mysql_client_test/7/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/release-8.5/job/pull_mysql_test/742/
-
https://prow.tidb.net/jenkins/job/pingcap/job/tidb/job/release-8.5/job/pull_sqllogic_test/4/

Signed-off-by: lyb <yebin.li@pingcap.com>